# -*- coding: utf-8 -*-
"""Ahmed Faroug.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aAoyQG4MuVdwcGIIfvVqND51tu6ULSxN
"""



from google.colab import drive

drive.mount('/content/drive')



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

dt = pd.read_csv('/content/drive/MyDrive/covid_worldwide.csv')

dt.head()

dt.describe()

dt.columns

dt.info()

dt.isnull().sum()

dt = dt.dropna()

dt.duplicated().sum()

dt.info()

dt.drop('Serial Number',axis='columns')

dt.tail()

dt.groupby(['Country']).sum()



dt = dt.head(10)

"""Countries with highest Covid Cases"""

plt.bar( dt['Country'], dt['Total Cases']);
  plt.xlabel("Country")
  plt.ylabel('Total Cases')
  plt.title('Countries with highest Covid Cases')
  plt.xticks(rotation=75)

"""Countries with highest Deaths"""

plt.bar( dt['Country'], dt['Total Deaths']);
 plt.xlabel("Country")
 plt.ylabel('Total Deaths')
 plt.title('Countries with highest Deaths')
 plt.xticks(rotation=75)

